### ISSUE TITLE
canonical URLs on Page basis

### ISSUE THREAD

**Issue by lerni** [DorsetDigital/silverstripe-canonical#1]
I've needed canonical-tag for SS3 with the ability to specify canonical URL on Page basis (ie blog-posts). If the Idea to override canonical-tag per Page make sense to you, I'm happy to PR once I need it on 4.x. See here to see what a mean: https://github.com/lerni/canonical

**Comment by lerni** [comment]
~~may [here](https://github.com/DorsetDigital/silverstripe-canonical/blob/master/src/SiteTreeCanonicalExtension.php#L15) just do this instead:
```if ($siteConfig->CanonicalDomain != '' || (method_exists($this->owner, 'CanonicalLink') && $this->owner->CanonicalLink() != '')) {```
...and let people do, whatever they want with `CanonicalLink()`? If this sounds sane to you, I'll PR and we can close this issue?~~
Scratch above. Now I use this: https://github.com/lerni/silverstripe-canonical

**Comment by DorsetDigital** [comment]
Now complete, released as 1.1
